In [1]:
import numpy as np

In [8]:
# Create a 1D NumPy array from list [10, 20, 30, 40, 50]
arr=np.array([10,20,30,40,50])
print(arr)


# Create a 3x3 array of ones
o=inp.ones([3,3])
print(o)

# Use arange to create an array from 5 to 45 with step of 5 np.arange(start,stop,step)
a=np.arange(5,45,5) # will generate integer values between 5 to 45 with a step of 5
print(a)

# Use linspace to divide the number 1 to 3 into 4 equal parts np.linspace(start,stop,n)
b=np.linspace(1,3,4) # will generate 4 float values between 1 to 3
print(b)

# Print shape, size, and type of any array
print(o.shape)
print(a.size)
print(b.dtype)

[10 20 30 40 50]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]
[ 5 10 15 20 25 30 35 40]
[1.         1.66666667 2.33333333 3.        ]
(3, 3)
8
float64


In [10]:
# Create a 2D NumPy array with values from 1 to 9
arr=np.arange(1,10)
print(arr)

# Reshape it into a 3x3 matrix
r=arr.reshape([3,3])
print(r)

# Print its shape, dimension (ndim), and data type (dtype)
print(r.shape)
print(r.ndim)
print(r.dtype)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
2
int32


In [2]:
# Create a NumPy array of numbers from 50 to 90 with a step size of 10. Print its shape and number of dimensions.
import numpy as np
arr=np.arange(50,90,10)
print(arr)
print(arr.shape)
print(arr.ndim)

[50 60 70 80]
(4,)
1


In [11]:
# Create a 4x4 array of zeros, then change its data type to int.

zeros=np.zeros([4,4])
integer=zeros.astype(int)
print(integer)
print(integer.dtype)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
int32


In [12]:
# Use linspace() to generate 6 equally spaced numbers between 10 and 20. Print the array and its data type.
a=np.linspace(10,20,6)
print(a)
print(a.dtype)

[10. 12. 14. 16. 18. 20.]
float64


In [21]:
# Create a 1D array from 1 to 12, then reshape it into:
# a 2D 3x4 array
# a 2D 4x3 array
# a 1D array again

arr1=np.arange(1,13,1)
print(arr1)
r1=arr1.reshape([3,4])
print(r1)
r2=arr1.reshape([4,3])
print(r2)
print(r2.flatten())

[ 1  2  3  4  5  6  7  8  9 10 11 12]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [22]:
# What will be the shape, size, and dtype of this array:
x=np.ones((2, 5)) * 3.14
print(x)
print(x.shape)
print(x.dtype)
print(x.size)
# It will be 2,5 only just all the one's will get multipled by 3.14

[[3.14 3.14 3.14 3.14 3.14]
 [3.14 3.14 3.14 3.14 3.14]]
(2, 5)
float64
10


# Indexing and Slicing 

Goal: Learn how to access individual elements, rows, columns, and sub-arrays from 2D arrays

In [24]:
z=np.arange(1,10).reshape([3,3])
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Indexing

In [25]:
z[0,0] # Row 1 col 1 element

1

In [28]:
z[1,2] # Row 1 col 2 element

6

In [29]:
z[2,1] # Row 2 col 1 element

8

## Slicing

In [30]:
z[0, :]     # → first row  all cols → [1 2 3]

array([1, 2, 3])

In [31]:
z[:, 1]     # → second column → [2 5 8]


array([2, 5, 8])

In [32]:
z[1:3, 1:]  # → sub-array: rows 1-2, cols 1-2 → [[5 6], [8 9]]


array([[5, 6],
       [8, 9]])

In [33]:
z[:2, :2]   # → top-left 2x2 → [[1 2], [4 5]]

array([[1, 2],
       [4, 5]])

In [35]:
a=np.arange(1,10).reshape([3,3])
print(a)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Write code to:

Print the last row

Print the middle column

Print the bottom-right element

Print the top-left 2x2 matrix

Extract the diagonal elements manually (no np.diag() yet)

In [36]:
# Print the last row
a[2,:] # Row 2 all cols

array([7, 8, 9])

In [37]:
# Print the middle column
a[:,1] # all rows col 1

array([2, 5, 8])

In [40]:
# Print the bottom-right element
a[2,2]

9

In [39]:
#Print the top-left 2x2 matrix
a[:2,:2]

array([[1, 2],
       [4, 5]])

In [42]:
# Extract the diagonal elements manually (no np.diag() yet)
# Remember for a square matrix row number == col number like row 0 col 0 , row 1 col 1
diagonal=[a[i,i] for i in range(3)]
print(diagonal)

[1, 5, 9]


In [44]:
diagonal2=[a[i,2-i] for i in range(3)] # to print 3*3 matrix anti diagonal elements
# a[0, 2] → 3
# a[1, 1] → 5
# a[2, 0] → 7
print(diagonal2)

[3, 5, 7]


# Fancy Indexing and Masking

In [45]:
import numpy as np


In [51]:
#From array [5, 10, 15, 20, 25, 30], use fancy indexing to print [10, 25, 30]
arr=np.array([5, 10, 15, 20, 25, 30])
print(arr[[1,4,5]])

#From same array, print all values greater than or equal to 15
print(arr[arr>=15])

#Given 2D array: Print all odd numbers using boolean masking
b=np.array([[1, 4, 7],
          [2, 5, 8],
          [3, 6, 9]])

print(b[b%2==1])

[10 25 30]
[15 20 25 30]
[1 7 5 3 9]
